on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to be able to publish to GitHub Packages
    name: Release
    uses: ./.github/workflows/reusable_release.yaml
    with:
      package_slug: wc-bulk-ai
      php_version: "8.2"
      build_assets: true
    secrets: inherit
